BOT_NAME = "matmuhbot"
SPIDER_MODULES = ["matmuhbot.spiders"]
NEWSPIDER_MODULE = "matmuhbot.spiders"

USER_AGENT = "matmuhbot/0.1 (+https://matmuh.yildiz.edu.tr)"
ROBOTSTXT_OBEY = True
DOWNLOAD_DELAY = 1.0
CONCURRENT_REQUESTS_PER_DOMAIN = 2
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 1.0
AUTOTHROTTLE_MAX_DELAY = 10.0

HTTPCACHE_ENABLED = True
HTTPCACHE_DIR = "httpcache"
HTTPCACHE_EXPIRATION_SECS = 86400

FEED_EXPORT_ENCODING = "utf-8"
FEED_EXPORT_INDENT = 1
REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
LOG_LEVEL = "INFO"
